spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  profiles:
    active: prod

server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET:1234}


